import { ThemeProvider } from "@/components/refine-ui/theme/theme-provider";
import type { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";
import "./globals.css";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Suspense>
          <ThemeProvider>
            <RefineContext>{children}</RefineContext>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
