import type { Metadata } from "next";
import React, { Suspense } from "react";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Suspense>
          <Providers>
            {/* <ThemeProvider> */}
              {/* <RefineContext> */}
                {children}
              {/* </RefineContext> */}
            {/* </ThemeProvider> */}
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
